version: "3.9"

services:
#  app:
#    container_name: app
#    build: ./backend
#    ports:
#      - "8080:7082"
#    depends_on:
#      - db
#    restart: always
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justinaio
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
volumes:
  data-postgres:
