version: "3.9"

services:
  app:
    container_name: backend
    build: ./backend
    ports:
      - "8080:7082"
    depends_on:
      - db
    restart: always
  web: 
    container_name: frontend
    build: ./frontend
    ports: 
      - "8090:8090"
    depends_on:
      - app
    restart: always
    environment: 
      VITE_API_ROUTE : http://app:8080/api/v1/
      VITE_API_LOGIN : login
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justinaio
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
volumes:
  data-postgres:
